# Site settings
title: FIPS 201
description: FIPS 201
baseurl: "/FIPS201" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- BUILD.md
- "*.yml"
- "*/images/*.pdf"

# GitHub information will uncomment ones names are finalized and NIST GitHub Pages resources have been allocated
#org_name: usnistgov
#repo_name: nistpages-shell

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
  collection: false
- text: Frontmatter
  url: /abstract/
  collection: Frontmatter
  anchor: abstract
- text: FIPS 201
  url: /introduction/
  collection: FIPS201
  anchor: s-1
- text: Appendices
  url: /accreditation/
  collection: Appendix
  anchor: s-a
  
  
collections:
  Frontmatter:
    output: true
  FIPS201:
    output: true
  Appendix:
    output: true

relative_links:
  enabled:     true
  collections: true

#Uncomment when we go live 
host: 0.0.0.0

include:
- _stylesheets
- _javascript

# Custom site configuration
lang: en
