# Site settings
title: FIPS 201
description: FIPS 201
baseurl: "/FIPS201" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- BUILD.md
- "*.yml"
- "*/images/*.pdf"

# GitHub information will uncomment ones names are finalized and NIST GitHub Pages resources have been allocated
org_name: usnistgov
repo_name: FIPS201

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
  collection: false
- text: FIPS 201
  url: /introduction/
  collection: FIPS201
  anchor: s-1
  
  
collections:
  FIPS201:
    output: true

relative_links:
  enabled:     true
  collections: true

#Uncomment when we go live 
host: 0.0.0.0

include:
- _stylesheets
- _javascript

# Custom site configuration
lang: en

abstract:
  subject: "This document establishes a standard for a Personal Identity Verification (PIV) system that meets the control and security objectives of Homeland Security Presidential Directive-12. It is based on secure and reliable forms of identity credentials issued by the Federal Government to its employees and contractors. These credentials are used by mechanisms that authenticate individuals who require access to federally controlled facilities, information systems, and applications. This Standard addresses requirements for initial identity proofing, infrastructure to support interoperability of identity credentials, and accreditation of organizations and processes issuing PIV credentials."
  keywords: 'authentication, authenticator, biometrics, credential, cryptography, derived PIV credentials, digital identity, Federal Information Processing Standards (FIPS), HSPD-12, federation, identification, identity proofing, integrated circuit card, Personal Identity Verification, PIV, PIV identity account, public key infrastructure, verification'
